# https://travis-ci.org/christoph2/pydbc
language: python
sudo: required
python:
    - 3.4
    - 3.5
    - 3.6
    #- "pypy"

os:
  - linux
  - osx

notifications:
  email: false


install:
  - sudo curl -O http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - export CLASSPATH=".:/home/travis/build/christoph2/pyA2L/antlr-4.7.1-complete.jar:$CLASSPATH"
  - alias antlr4='java -jar /usr/local/lib/antlr-4.7-complete.jar'
  - pip install -r requirements_testing.txt
  - travis_retry pip install pylint
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage


script:
   coverage run --source=pydbc setup.py test

after_success:
  - pylint app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
